/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Hoge */

#ifndef _Included_Hoge
#define _Included_Hoge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Hoge
 * Method:    getNumber
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Hoge_getNumber
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
